// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	AgentRequest
	AgentResponse
	ProbeRequest
	ProbeResponse
	ScheduleProbeRequest
	ScheduleProbeResponse
	AgentMessage
	AgentInfo
	AgentProbeResult
	ControllerMessage
	LatencyRequest
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentMessage_Type int32

const (
	AgentMessage_HELLO  AgentMessage_Type = 0
	AgentMessage_RESULT AgentMessage_Type = 1
	AgentMessage_INFO   AgentMessage_Type = 2
)

var AgentMessage_Type_name = map[int32]string{
	0: "HELLO",
	1: "RESULT",
	2: "INFO",
}
var AgentMessage_Type_value = map[string]int32{
	"HELLO":  0,
	"RESULT": 1,
	"INFO":   2,
}

func (x AgentMessage_Type) String() string {
	return proto.EnumName(AgentMessage_Type_name, int32(x))
}
func (AgentMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type AgentProbeResult_Type int32

const (
	AgentProbeResult_TCP        AgentProbeResult_Type = 0
	AgentProbeResult_ICMP       AgentProbeResult_Type = 1
	AgentProbeResult_TRACEROUTE AgentProbeResult_Type = 2
)

var AgentProbeResult_Type_name = map[int32]string{
	0: "TCP",
	1: "ICMP",
	2: "TRACEROUTE",
}
var AgentProbeResult_Type_value = map[string]int32{
	"TCP":        0,
	"ICMP":       1,
	"TRACEROUTE": 2,
}

func (x AgentProbeResult_Type) String() string {
	return proto.EnumName(AgentProbeResult_Type_name, int32(x))
}
func (AgentProbeResult_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type ControllerMessage_Type int32

const (
	ControllerMessage_AGENT_INFO_REQUEST ControllerMessage_Type = 0
	ControllerMessage_LATENCY_REQUEST    ControllerMessage_Type = 1
)

var ControllerMessage_Type_name = map[int32]string{
	0: "AGENT_INFO_REQUEST",
	1: "LATENCY_REQUEST",
}
var ControllerMessage_Type_value = map[string]int32{
	"AGENT_INFO_REQUEST": 0,
	"LATENCY_REQUEST":    1,
}

func (x ControllerMessage_Type) String() string {
	return proto.EnumName(ControllerMessage_Type_name, int32(x))
}
func (ControllerMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type LatencyRequest_Type int32

const (
	LatencyRequest_TCP        LatencyRequest_Type = 0
	LatencyRequest_ICMP       LatencyRequest_Type = 1
	LatencyRequest_TRACEROUTE LatencyRequest_Type = 2
)

var LatencyRequest_Type_name = map[int32]string{
	0: "TCP",
	1: "ICMP",
	2: "TRACEROUTE",
}
var LatencyRequest_Type_value = map[string]int32{
	"TCP":        0,
	"ICMP":       1,
	"TRACEROUTE": 2,
}

func (x LatencyRequest_Type) String() string {
	return proto.EnumName(LatencyRequest_Type_name, int32(x))
}
func (LatencyRequest_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

type AgentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AgentRequest) Reset()                    { *m = AgentRequest{} }
func (m *AgentRequest) String() string            { return proto.CompactTextString(m) }
func (*AgentRequest) ProtoMessage()               {}
func (*AgentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AgentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AgentResponse struct {
	Agents map[string]*AgentInfo `protobuf:"bytes,1,rep,name=agents" json:"agents,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AgentResponse) Reset()                    { *m = AgentResponse{} }
func (m *AgentResponse) String() string            { return proto.CompactTextString(m) }
func (*AgentResponse) ProtoMessage()               {}
func (*AgentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AgentResponse) GetAgents() map[string]*AgentInfo {
	if m != nil {
		return m.Agents
	}
	return nil
}

type ProbeRequest struct {
	AgentId        string          `protobuf:"bytes,1,opt,name=agentId" json:"agentId,omitempty"`
	Repeat         bool            `protobuf:"varint,2,opt,name=repeat" json:"repeat,omitempty"`
	LatencyRequest *LatencyRequest `protobuf:"bytes,3,opt,name=latencyRequest" json:"latencyRequest,omitempty"`
}

func (m *ProbeRequest) Reset()                    { *m = ProbeRequest{} }
func (m *ProbeRequest) String() string            { return proto.CompactTextString(m) }
func (*ProbeRequest) ProtoMessage()               {}
func (*ProbeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProbeRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *ProbeRequest) GetRepeat() bool {
	if m != nil {
		return m.Repeat
	}
	return false
}

func (m *ProbeRequest) GetLatencyRequest() *LatencyRequest {
	if m != nil {
		return m.LatencyRequest
	}
	return nil
}

type ProbeResponse struct {
	Result *AgentProbeResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ProbeResponse) Reset()                    { *m = ProbeResponse{} }
func (m *ProbeResponse) String() string            { return proto.CompactTextString(m) }
func (*ProbeResponse) ProtoMessage()               {}
func (*ProbeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProbeResponse) GetResult() *AgentProbeResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ScheduleProbeRequest struct {
}

func (m *ScheduleProbeRequest) Reset()                    { *m = ScheduleProbeRequest{} }
func (m *ScheduleProbeRequest) String() string            { return proto.CompactTextString(m) }
func (*ScheduleProbeRequest) ProtoMessage()               {}
func (*ScheduleProbeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ScheduleProbeResponse struct {
}

func (m *ScheduleProbeResponse) Reset()                    { *m = ScheduleProbeResponse{} }
func (m *ScheduleProbeResponse) String() string            { return proto.CompactTextString(m) }
func (*ScheduleProbeResponse) ProtoMessage()               {}
func (*ScheduleProbeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type AgentMessage struct {
	Type   AgentMessage_Type `protobuf:"varint,1,opt,name=type,enum=messages.AgentMessage_Type" json:"type,omitempty"`
	Id     string            `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Auth   string            `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
	Result *AgentProbeResult `protobuf:"bytes,4,opt,name=result" json:"result,omitempty"`
	Info   *AgentInfo        `protobuf:"bytes,5,opt,name=info" json:"info,omitempty"`
}

func (m *AgentMessage) Reset()                    { *m = AgentMessage{} }
func (m *AgentMessage) String() string            { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()               {}
func (*AgentMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *AgentMessage) GetType() AgentMessage_Type {
	if m != nil {
		return m.Type
	}
	return AgentMessage_HELLO
}

func (m *AgentMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentMessage) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *AgentMessage) GetResult() *AgentProbeResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AgentMessage) GetInfo() *AgentInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type AgentInfo struct {
	Os           string `protobuf:"bytes,1,opt,name=os" json:"os,omitempty"`
	Hostname     string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	AgentVersion string `protobuf:"bytes,3,opt,name=agentVersion" json:"agentVersion,omitempty"`
	Ipaddress    string `protobuf:"bytes,4,opt,name=ipaddress" json:"ipaddress,omitempty"`
	Label        string `protobuf:"bytes,5,opt,name=label" json:"label,omitempty"`
	Location     string `protobuf:"bytes,6,opt,name=location" json:"location,omitempty"`
}

func (m *AgentInfo) Reset()                    { *m = AgentInfo{} }
func (m *AgentInfo) String() string            { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()               {}
func (*AgentInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *AgentInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *AgentInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentInfo) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentInfo) GetIpaddress() string {
	if m != nil {
		return m.Ipaddress
	}
	return ""
}

func (m *AgentInfo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AgentInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type AgentProbeResult struct {
	Type         AgentProbeResult_Type `protobuf:"varint,1,opt,name=type,enum=messages.AgentProbeResult_Type" json:"type,omitempty"`
	ResultId     string                `protobuf:"bytes,2,opt,name=resultId" json:"resultId,omitempty"`
	Host         string                `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	ProbeId      string                `protobuf:"bytes,4,opt,name=probeId" json:"probeId,omitempty"`
	Timestamp    int64                 `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Data         []byte                `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Error        bool                  `protobuf:"varint,7,opt,name=error" json:"error,omitempty"`
	ErrorMessage string                `protobuf:"bytes,8,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *AgentProbeResult) Reset()                    { *m = AgentProbeResult{} }
func (m *AgentProbeResult) String() string            { return proto.CompactTextString(m) }
func (*AgentProbeResult) ProtoMessage()               {}
func (*AgentProbeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *AgentProbeResult) GetType() AgentProbeResult_Type {
	if m != nil {
		return m.Type
	}
	return AgentProbeResult_TCP
}

func (m *AgentProbeResult) GetResultId() string {
	if m != nil {
		return m.ResultId
	}
	return ""
}

func (m *AgentProbeResult) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AgentProbeResult) GetProbeId() string {
	if m != nil {
		return m.ProbeId
	}
	return ""
}

func (m *AgentProbeResult) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AgentProbeResult) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AgentProbeResult) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *AgentProbeResult) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ControllerMessage struct {
	Type           ControllerMessage_Type `protobuf:"varint,1,opt,name=type,enum=messages.ControllerMessage_Type" json:"type,omitempty"`
	LatencyRequest *LatencyRequest        `protobuf:"bytes,2,opt,name=latencyRequest" json:"latencyRequest,omitempty"`
}

func (m *ControllerMessage) Reset()                    { *m = ControllerMessage{} }
func (m *ControllerMessage) String() string            { return proto.CompactTextString(m) }
func (*ControllerMessage) ProtoMessage()               {}
func (*ControllerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ControllerMessage) GetType() ControllerMessage_Type {
	if m != nil {
		return m.Type
	}
	return ControllerMessage_AGENT_INFO_REQUEST
}

func (m *ControllerMessage) GetLatencyRequest() *LatencyRequest {
	if m != nil {
		return m.LatencyRequest
	}
	return nil
}

type LatencyRequest struct {
	Type       LatencyRequest_Type `protobuf:"varint,1,opt,name=type,enum=messages.LatencyRequest_Type" json:"type,omitempty"`
	ResultId   string              `protobuf:"bytes,2,opt,name=resultId" json:"resultId,omitempty"`
	Host       string              `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Parameters map[string]string   `protobuf:"bytes,4,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *LatencyRequest) Reset()                    { *m = LatencyRequest{} }
func (m *LatencyRequest) String() string            { return proto.CompactTextString(m) }
func (*LatencyRequest) ProtoMessage()               {}
func (*LatencyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *LatencyRequest) GetType() LatencyRequest_Type {
	if m != nil {
		return m.Type
	}
	return LatencyRequest_TCP
}

func (m *LatencyRequest) GetResultId() string {
	if m != nil {
		return m.ResultId
	}
	return ""
}

func (m *LatencyRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *LatencyRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentRequest)(nil), "messages.AgentRequest")
	proto.RegisterType((*AgentResponse)(nil), "messages.AgentResponse")
	proto.RegisterType((*ProbeRequest)(nil), "messages.ProbeRequest")
	proto.RegisterType((*ProbeResponse)(nil), "messages.ProbeResponse")
	proto.RegisterType((*ScheduleProbeRequest)(nil), "messages.ScheduleProbeRequest")
	proto.RegisterType((*ScheduleProbeResponse)(nil), "messages.ScheduleProbeResponse")
	proto.RegisterType((*AgentMessage)(nil), "messages.AgentMessage")
	proto.RegisterType((*AgentInfo)(nil), "messages.AgentInfo")
	proto.RegisterType((*AgentProbeResult)(nil), "messages.AgentProbeResult")
	proto.RegisterType((*ControllerMessage)(nil), "messages.ControllerMessage")
	proto.RegisterType((*LatencyRequest)(nil), "messages.LatencyRequest")
	proto.RegisterEnum("messages.AgentMessage_Type", AgentMessage_Type_name, AgentMessage_Type_value)
	proto.RegisterEnum("messages.AgentProbeResult_Type", AgentProbeResult_Type_name, AgentProbeResult_Type_value)
	proto.RegisterEnum("messages.ControllerMessage_Type", ControllerMessage_Type_name, ControllerMessage_Type_value)
	proto.RegisterEnum("messages.LatencyRequest_Type", LatencyRequest_Type_name, LatencyRequest_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Controller service

type ControllerClient interface {
	GetAgents(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentResponse, error)
	SendProbe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResponse, error)
	ScheduleProbe(ctx context.Context, in *ScheduleProbeRequest, opts ...grpc.CallOption) (*ScheduleProbeResponse, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) GetAgents(ctx context.Context, in *AgentRequest, opts ...grpc.CallOption) (*AgentResponse, error) {
	out := new(AgentResponse)
	err := grpc.Invoke(ctx, "/messages.Controller/GetAgents", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) SendProbe(ctx context.Context, in *ProbeRequest, opts ...grpc.CallOption) (*ProbeResponse, error) {
	out := new(ProbeResponse)
	err := grpc.Invoke(ctx, "/messages.Controller/SendProbe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ScheduleProbe(ctx context.Context, in *ScheduleProbeRequest, opts ...grpc.CallOption) (*ScheduleProbeResponse, error) {
	out := new(ScheduleProbeResponse)
	err := grpc.Invoke(ctx, "/messages.Controller/ScheduleProbe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Controller service

type ControllerServer interface {
	GetAgents(context.Context, *AgentRequest) (*AgentResponse, error)
	SendProbe(context.Context, *ProbeRequest) (*ProbeResponse, error)
	ScheduleProbe(context.Context, *ScheduleProbeRequest) (*ScheduleProbeResponse, error)
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_GetAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).GetAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Controller/GetAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).GetAgents(ctx, req.(*AgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_SendProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SendProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Controller/SendProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SendProbe(ctx, req.(*ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ScheduleProbe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ScheduleProbe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messages.Controller/ScheduleProbe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ScheduleProbe(ctx, req.(*ScheduleProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messages.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgents",
			Handler:    _Controller_GetAgents_Handler,
		},
		{
			MethodName: "SendProbe",
			Handler:    _Controller_SendProbe_Handler,
		},
		{
			MethodName: "ScheduleProbe",
			Handler:    _Controller_ScheduleProbe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messages.proto",
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xdb, 0x38,
	0x10, 0x8e, 0xe4, 0x9f, 0x58, 0x63, 0xc7, 0xd1, 0x32, 0x59, 0x47, 0xf0, 0xee, 0x26, 0x86, 0xf6,
	0x10, 0xe7, 0x92, 0xc5, 0x3a, 0x7b, 0x58, 0xec, 0x0f, 0x50, 0xc3, 0x50, 0x13, 0x03, 0x8e, 0xe3,
	0xd2, 0x4a, 0x81, 0x9e, 0x02, 0x26, 0x62, 0x12, 0xa3, 0xb2, 0xa4, 0x8a, 0x74, 0x01, 0x5f, 0xfb,
	0x1c, 0xbd, 0xb7, 0x40, 0x5f, 0xa2, 0xcf, 0xd1, 0x37, 0xe8, 0x5b, 0x14, 0xa4, 0x28, 0x5b, 0x72,
	0x62, 0x20, 0x45, 0x6f, 0x9c, 0xe1, 0x70, 0xbe, 0xf9, 0xe6, 0x23, 0x87, 0x50, 0x9f, 0x52, 0xc6,
	0xc8, 0x1d, 0x65, 0xc7, 0x51, 0x1c, 0xf2, 0x10, 0x55, 0x52, 0xdb, 0xde, 0x87, 0x5a, 0xf7, 0x8e,
	0x06, 0x1c, 0xd3, 0x37, 0x33, 0xca, 0x38, 0xaa, 0x83, 0x3e, 0xf1, 0x2c, 0xad, 0xa5, 0xb5, 0x0d,
	0xac, 0x4f, 0x3c, 0xfb, 0xbd, 0x06, 0x5b, 0x2a, 0x80, 0x45, 0x61, 0xc0, 0x28, 0xfa, 0x17, 0xca,
	0x44, 0x38, 0x98, 0xa5, 0xb5, 0x0a, 0xed, 0x6a, 0xe7, 0xf7, 0xe3, 0x45, 0xf2, 0x5c, 0x60, 0x62,
	0x31, 0x27, 0xe0, 0xf1, 0x1c, 0xab, 0x23, 0xcd, 0x21, 0x54, 0x33, 0x6e, 0x64, 0x42, 0xe1, 0x35,
	0x9d, 0x2b, 0x38, 0xb1, 0x44, 0x47, 0x50, 0x7a, 0x4b, 0xfc, 0x19, 0xb5, 0xf4, 0x96, 0xd6, 0xae,
	0x76, 0x76, 0x56, 0x92, 0xf7, 0x83, 0xdb, 0x10, 0x27, 0x11, 0xff, 0xe8, 0x7f, 0x6b, 0xf6, 0x3b,
	0x0d, 0x6a, 0xa3, 0x38, 0xbc, 0xa6, 0x69, 0xfd, 0x16, 0x6c, 0x4a, 0xa8, 0x7e, 0x4a, 0x22, 0x35,
	0x51, 0x03, 0xca, 0x31, 0x8d, 0x28, 0xe1, 0x32, 0x75, 0x05, 0x2b, 0x0b, 0x3d, 0x83, 0xba, 0x4f,
	0x38, 0x0d, 0x6e, 0xe6, 0x2a, 0x87, 0x55, 0x90, 0xd0, 0xd6, 0x12, 0x7a, 0x90, 0xdb, 0xc7, 0x2b,
	0xf1, 0x76, 0x0f, 0xb6, 0x54, 0x0d, 0xaa, 0x45, 0x1d, 0x01, 0xc5, 0x66, 0x3e, 0x97, 0x35, 0x54,
	0x3b, 0xcd, 0x15, 0x16, 0x69, 0xf4, 0xcc, 0xe7, 0x58, 0x45, 0xda, 0x0d, 0xd8, 0x1d, 0xdf, 0xdc,
	0x53, 0x6f, 0xe6, 0xd3, 0x2c, 0x21, 0x7b, 0x0f, 0x7e, 0x5e, 0xf1, 0x27, 0x20, 0xf6, 0x57, 0x4d,
	0x49, 0x77, 0x9e, 0xe4, 0x46, 0x7f, 0x40, 0x91, 0xcf, 0x23, 0x2a, 0x31, 0xeb, 0x9d, 0x5f, 0x56,
	0x30, 0x55, 0xd4, 0xb1, 0x3b, 0x8f, 0x28, 0x96, 0x81, 0x4a, 0x6b, 0x3d, 0xd5, 0x1a, 0x21, 0x28,
	0x92, 0x19, 0xbf, 0x97, 0xfc, 0x0d, 0x2c, 0xd7, 0x19, 0x2a, 0xc5, 0xa7, 0x52, 0x41, 0x87, 0x50,
	0x9c, 0x04, 0xb7, 0xa1, 0x55, 0x5a, 0x2f, 0xa1, 0x0c, 0xb0, 0x0f, 0xa1, 0x28, 0xca, 0x41, 0x06,
	0x94, 0xce, 0x9c, 0xc1, 0xe0, 0xc2, 0xdc, 0x40, 0x00, 0x65, 0xec, 0x8c, 0x2f, 0x07, 0xae, 0xa9,
	0xa1, 0x0a, 0x14, 0xfb, 0xc3, 0xe7, 0x17, 0xa6, 0x6e, 0x7f, 0xd2, 0xc0, 0x58, 0x1c, 0x16, 0x75,
	0x87, 0x2c, 0xbd, 0xa3, 0x21, 0x43, 0x4d, 0xa8, 0xdc, 0x87, 0x8c, 0x07, 0x64, 0x4a, 0x15, 0x9b,
	0x85, 0x8d, 0x6c, 0xa8, 0xc9, 0x0b, 0xf0, 0x92, 0xc6, 0x6c, 0x12, 0x06, 0x8a, 0x5b, 0xce, 0x87,
	0x7e, 0x05, 0x63, 0x12, 0x11, 0xcf, 0x8b, 0x29, 0x63, 0x92, 0xa6, 0x81, 0x97, 0x0e, 0xb4, 0x0b,
	0x25, 0x9f, 0x5c, 0x53, 0x5f, 0xd2, 0x31, 0x70, 0x62, 0x08, 0x4c, 0x3f, 0xbc, 0x21, 0x5c, 0xe4,
	0x2c, 0x27, 0x98, 0xa9, 0x6d, 0x7f, 0xd4, 0xc1, 0x5c, 0x6d, 0x0e, 0x3a, 0xc9, 0xa9, 0x73, 0xb0,
	0xbe, 0x8d, 0x59, 0x85, 0x9a, 0x50, 0x49, 0x7a, 0xda, 0x4f, 0x75, 0x5a, 0xd8, 0x42, 0x2d, 0xc1,
	0x32, 0x55, 0x4b, 0xac, 0xc5, 0xed, 0x8f, 0x44, 0xa6, 0xbe, 0xa7, 0x78, 0xa4, 0xa6, 0xe0, 0xc8,
	0x27, 0x53, 0xca, 0x38, 0x99, 0x46, 0x92, 0x49, 0x01, 0x2f, 0x1d, 0x22, 0x97, 0x47, 0x38, 0x91,
	0x4c, 0x6a, 0x58, 0xae, 0x05, 0x6f, 0x1a, 0xc7, 0x61, 0x6c, 0x6d, 0xca, 0xe7, 0x92, 0x18, 0xa2,
	0x9f, 0x72, 0xa1, 0xae, 0x93, 0x55, 0x49, 0xfa, 0x99, 0xf5, 0xd9, 0x47, 0x4a, 0xd6, 0x4d, 0x28,
	0xb8, 0xbd, 0x91, 0xb9, 0x21, 0x85, 0xec, 0x9d, 0x8f, 0x4c, 0x0d, 0xd5, 0x01, 0x5c, 0xdc, 0xed,
	0x39, 0xf8, 0xe2, 0xd2, 0x75, 0x4c, 0xdd, 0xfe, 0xac, 0xc1, 0x4f, 0xbd, 0x30, 0xe0, 0x71, 0xe8,
	0xfb, 0x34, 0x4d, 0x80, 0xfe, 0xca, 0xf5, 0xaa, 0xb5, 0xec, 0xd5, 0x83, 0xd0, 0x6c, 0xb3, 0x1e,
	0x3e, 0x64, 0xfd, 0x3b, 0x1f, 0xf2, 0x89, 0x2a, 0xbc, 0x01, 0xa8, 0x7b, 0xea, 0x0c, 0xdd, 0x2b,
	0x71, 0xfd, 0xae, 0xb0, 0xf3, 0xe2, 0xd2, 0x19, 0xbb, 0xe6, 0x06, 0xda, 0x81, 0xed, 0x41, 0xd7,
	0x75, 0x86, 0xbd, 0x57, 0x0b, 0xa7, 0x66, 0x7f, 0xd0, 0xa1, 0x9e, 0xcf, 0x8b, 0xfe, 0xcc, 0xd5,
	0xff, 0xdb, 0x3a, 0xfc, 0x1f, 0x51, 0xfa, 0x0c, 0x20, 0x22, 0x31, 0x99, 0x52, 0x4e, 0x63, 0x71,
	0x69, 0xc5, 0x24, 0x6e, 0xaf, 0x05, 0x1a, 0x2d, 0x42, 0x93, 0x71, 0x9c, 0x39, 0xdb, 0xfc, 0x1f,
	0xb6, 0x57, 0xb6, 0x1f, 0x19, 0xcb, 0xbb, 0xd9, 0xb1, 0x6c, 0x64, 0x27, 0xf0, 0xd3, 0xc5, 0xee,
	0x7c, 0xd1, 0x00, 0x96, 0x0a, 0xa2, 0xff, 0xc0, 0x38, 0xa5, 0x3c, 0xf9, 0x0e, 0x50, 0xe3, 0xc1,
	0x2f, 0x22, 0x2b, 0x6f, 0xee, 0xad, 0xf9, 0x5d, 0xc4, 0xe9, 0x31, 0x0d, 0x3c, 0xf9, 0x70, 0xb2,
	0xa7, 0xb3, 0xc3, 0x33, 0x7b, 0x3a, 0x3f, 0xa1, 0x47, 0xb0, 0x95, 0x9b, 0xaa, 0x68, 0x7f, 0x19,
	0xf9, 0xd8, 0x18, 0x6e, 0x1e, 0xac, 0xdd, 0x4f, 0x32, 0x5e, 0x97, 0xe5, 0xcf, 0x7a, 0xf2, 0x2d,
	0x00, 0x00, 0xff, 0xff, 0xab, 0xc6, 0x0b, 0x57, 0x6b, 0x07, 0x00, 0x00,
}
