// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ProbeACK
	ProbeResult
	ProbeCommand
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProbeACK_Type int32

const (
	ProbeACK_HELLO  ProbeACK_Type = 0
	ProbeACK_RESULT ProbeACK_Type = 1
)

var ProbeACK_Type_name = map[int32]string{
	0: "HELLO",
	1: "RESULT",
}
var ProbeACK_Type_value = map[string]int32{
	"HELLO":  0,
	"RESULT": 1,
}

func (x ProbeACK_Type) String() string {
	return proto.EnumName(ProbeACK_Type_name, int32(x))
}
func (ProbeACK_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type ProbeResult_Type int32

const (
	ProbeResult_NOOP ProbeResult_Type = 0
	ProbeResult_TCP  ProbeResult_Type = 1
	ProbeResult_ICMP ProbeResult_Type = 2
)

var ProbeResult_Type_name = map[int32]string{
	0: "NOOP",
	1: "TCP",
	2: "ICMP",
}
var ProbeResult_Type_value = map[string]int32{
	"NOOP": 0,
	"TCP":  1,
	"ICMP": 2,
}

func (x ProbeResult_Type) String() string {
	return proto.EnumName(ProbeResult_Type_name, int32(x))
}
func (ProbeResult_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type ProbeCommand_Type int32

const (
	ProbeCommand_NOOP ProbeCommand_Type = 0
	ProbeCommand_TCP  ProbeCommand_Type = 1
	ProbeCommand_ICMP ProbeCommand_Type = 2
)

var ProbeCommand_Type_name = map[int32]string{
	0: "NOOP",
	1: "TCP",
	2: "ICMP",
}
var ProbeCommand_Type_value = map[string]int32{
	"NOOP": 0,
	"TCP":  1,
	"ICMP": 2,
}

func (x ProbeCommand_Type) String() string {
	return proto.EnumName(ProbeCommand_Type_name, int32(x))
}
func (ProbeCommand_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type ProbeACK struct {
	Type   ProbeACK_Type `protobuf:"varint,1,opt,name=type,enum=messages.ProbeACK_Type" json:"type,omitempty"`
	Id     string        `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Auth   string        `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
	Label  string        `protobuf:"bytes,4,opt,name=label" json:"label,omitempty"`
	Result *ProbeResult  `protobuf:"bytes,5,opt,name=result" json:"result,omitempty"`
}

func (m *ProbeACK) Reset()                    { *m = ProbeACK{} }
func (m *ProbeACK) String() string            { return proto.CompactTextString(m) }
func (*ProbeACK) ProtoMessage()               {}
func (*ProbeACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProbeACK) GetType() ProbeACK_Type {
	if m != nil {
		return m.Type
	}
	return ProbeACK_HELLO
}

func (m *ProbeACK) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProbeACK) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *ProbeACK) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ProbeACK) GetResult() *ProbeResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type ProbeResult struct {
	Type      ProbeResult_Type `protobuf:"varint,1,opt,name=type,enum=messages.ProbeResult_Type" json:"type,omitempty"`
	CmdId     string           `protobuf:"bytes,2,opt,name=cmdId" json:"cmdId,omitempty"`
	Host      string           `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	ProbeId   string           `protobuf:"bytes,4,opt,name=probeId" json:"probeId,omitempty"`
	Timestamp int64            `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Data      []byte           `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ProbeResult) Reset()                    { *m = ProbeResult{} }
func (m *ProbeResult) String() string            { return proto.CompactTextString(m) }
func (*ProbeResult) ProtoMessage()               {}
func (*ProbeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProbeResult) GetType() ProbeResult_Type {
	if m != nil {
		return m.Type
	}
	return ProbeResult_NOOP
}

func (m *ProbeResult) GetCmdId() string {
	if m != nil {
		return m.CmdId
	}
	return ""
}

func (m *ProbeResult) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ProbeResult) GetProbeId() string {
	if m != nil {
		return m.ProbeId
	}
	return ""
}

func (m *ProbeResult) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProbeResult) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProbeCommand struct {
	Id         string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Host       string            `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Type       ProbeCommand_Type `protobuf:"varint,3,opt,name=type,enum=messages.ProbeCommand_Type" json:"type,omitempty"`
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ProbeCommand) Reset()                    { *m = ProbeCommand{} }
func (m *ProbeCommand) String() string            { return proto.CompactTextString(m) }
func (*ProbeCommand) ProtoMessage()               {}
func (*ProbeCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProbeCommand) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProbeCommand) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ProbeCommand) GetType() ProbeCommand_Type {
	if m != nil {
		return m.Type
	}
	return ProbeCommand_NOOP
}

func (m *ProbeCommand) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*ProbeACK)(nil), "messages.ProbeACK")
	proto.RegisterType((*ProbeResult)(nil), "messages.ProbeResult")
	proto.RegisterType((*ProbeCommand)(nil), "messages.ProbeCommand")
	proto.RegisterEnum("messages.ProbeACK_Type", ProbeACK_Type_name, ProbeACK_Type_value)
	proto.RegisterEnum("messages.ProbeResult_Type", ProbeResult_Type_name, ProbeResult_Type_value)
	proto.RegisterEnum("messages.ProbeCommand_Type", ProbeCommand_Type_name, ProbeCommand_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdd, 0x4a, 0xe3, 0x40,
	0x14, 0xc7, 0x3b, 0xf9, 0x6a, 0x7b, 0x5a, 0xba, 0x61, 0xe8, 0xb2, 0x43, 0x77, 0x17, 0x42, 0x16,
	0x96, 0xc0, 0xb2, 0x59, 0xe8, 0xde, 0x88, 0xe0, 0x85, 0x84, 0x8a, 0xc5, 0x6a, 0xc3, 0x58, 0x1f,
	0x60, 0x6a, 0x06, 0x5b, 0x4c, 0x9a, 0x90, 0x4c, 0x85, 0x3c, 0x85, 0x8f, 0xe4, 0x6b, 0xf8, 0x38,
	0x32, 0xd3, 0xa4, 0xc6, 0xa2, 0xe0, 0xdd, 0xf9, 0x9f, 0x39, 0x5f, 0xbf, 0x3f, 0x03, 0x83, 0x84,
	0x17, 0x05, 0xbb, 0xe3, 0x85, 0x9f, 0xe5, 0xa9, 0x48, 0x71, 0xa7, 0xd6, 0xee, 0x13, 0x82, 0x4e,
	0x98, 0xa7, 0x4b, 0x7e, 0x1a, 0x5c, 0xe0, 0x3f, 0x60, 0x88, 0x32, 0xe3, 0x04, 0x39, 0xc8, 0x1b,
	0x8c, 0xbf, 0xf9, 0xfb, 0xae, 0xba, 0xc2, 0x5f, 0x94, 0x19, 0xa7, 0xaa, 0x08, 0x0f, 0x40, 0x5b,
	0x47, 0x44, 0x73, 0x90, 0xd7, 0xa5, 0xda, 0x3a, 0xc2, 0x18, 0x0c, 0xb6, 0x15, 0x2b, 0xa2, 0xab,
	0x8c, 0x8a, 0xf1, 0x10, 0xcc, 0x98, 0x2d, 0x79, 0x4c, 0x0c, 0x95, 0xdc, 0x09, 0xfc, 0x17, 0xac,
	0x9c, 0x17, 0xdb, 0x58, 0x10, 0xd3, 0x41, 0x5e, 0x6f, 0xfc, 0xf5, 0x60, 0x11, 0x55, 0x8f, 0xb4,
	0x2a, 0x72, 0x7f, 0x82, 0x21, 0xd7, 0xe2, 0x2e, 0x98, 0xe7, 0x93, 0xd9, 0x6c, 0x6e, 0xb7, 0x30,
	0x80, 0x45, 0x27, 0xd7, 0x37, 0xb3, 0x85, 0x8d, 0xdc, 0x67, 0x04, 0xbd, 0x46, 0x1b, 0xf6, 0xdf,
	0x40, 0x8c, 0xde, 0x9d, 0xdd, 0xe4, 0x18, 0x82, 0x79, 0x9b, 0x44, 0xd3, 0x1a, 0x65, 0x27, 0x24,
	0xcd, 0x2a, 0x2d, 0x44, 0x4d, 0x23, 0x63, 0x4c, 0xa0, 0x9d, 0xc9, 0x19, 0xd3, 0xa8, 0xe2, 0xa9,
	0x25, 0xfe, 0x01, 0x5d, 0xb1, 0x4e, 0x78, 0x21, 0x58, 0x92, 0x29, 0x28, 0x9d, 0xbe, 0x26, 0xe4,
	0xac, 0x88, 0x09, 0x46, 0x2c, 0x07, 0x79, 0x7d, 0xaa, 0x62, 0xf7, 0x57, 0x05, 0xd5, 0x01, 0xe3,
	0x6a, 0x3e, 0x0f, 0xed, 0x16, 0x6e, 0x83, 0xbe, 0x08, 0x42, 0x1b, 0xc9, 0xd4, 0x34, 0xb8, 0x0c,
	0x6d, 0xcd, 0x7d, 0xd4, 0xa0, 0xaf, 0xae, 0x0e, 0xd2, 0x24, 0x61, 0x9b, 0xa8, 0xf2, 0x1c, 0x35,
	0x3d, 0x57, 0x57, 0x6a, 0x8d, 0x2b, 0xff, 0x55, 0xfc, 0xba, 0xe2, 0xff, 0x7e, 0xc0, 0x5f, 0x4d,
	0x6a, 0x1a, 0x70, 0x06, 0x90, 0xb1, 0x9c, 0x25, 0x5c, 0xf0, 0xbc, 0x20, 0x86, 0xa3, 0x7b, 0xbd,
	0xf1, 0xef, 0x0f, 0xda, 0xc2, 0x7d, 0xe1, 0x64, 0x23, 0xf2, 0x92, 0x36, 0x3a, 0x47, 0x27, 0xf0,
	0xe5, 0xe0, 0x19, 0xdb, 0xa0, 0xdf, 0xf3, 0xb2, 0x3a, 0x58, 0x86, 0xd2, 0xed, 0x07, 0x16, 0x6f,
	0x79, 0xed, 0xb6, 0x12, 0xc7, 0xda, 0x11, 0xfa, 0x94, 0x23, 0x4b, 0x4b, 0xfd, 0xdf, 0xff, 0x2f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x65, 0x52, 0xd7, 0x73, 0xd1, 0x02, 0x00, 0x00,
}
