// Code generated by protoc-gen-go.
// source: messages.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	AgentMessage
	AgentInfo
	AgentProbeResult
	ControllerMessage
	ControllerLatencyRequest
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentMessage_Type int32

const (
	AgentMessage_HELLO  AgentMessage_Type = 0
	AgentMessage_RESULT AgentMessage_Type = 1
	AgentMessage_INFO   AgentMessage_Type = 2
)

var AgentMessage_Type_name = map[int32]string{
	0: "HELLO",
	1: "RESULT",
	2: "INFO",
}
var AgentMessage_Type_value = map[string]int32{
	"HELLO":  0,
	"RESULT": 1,
	"INFO":   2,
}

func (x AgentMessage_Type) String() string {
	return proto.EnumName(AgentMessage_Type_name, int32(x))
}
func (AgentMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type AgentProbeResult_Type int32

const (
	AgentProbeResult_TCP        AgentProbeResult_Type = 0
	AgentProbeResult_ICMP       AgentProbeResult_Type = 1
	AgentProbeResult_TRACEROUTE AgentProbeResult_Type = 2
)

var AgentProbeResult_Type_name = map[int32]string{
	0: "TCP",
	1: "ICMP",
	2: "TRACEROUTE",
}
var AgentProbeResult_Type_value = map[string]int32{
	"TCP":        0,
	"ICMP":       1,
	"TRACEROUTE": 2,
}

func (x AgentProbeResult_Type) String() string {
	return proto.EnumName(AgentProbeResult_Type_name, int32(x))
}
func (AgentProbeResult_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type ControllerMessage_Type int32

const (
	ControllerMessage_AGENT_INFO_REQUEST ControllerMessage_Type = 0
	ControllerMessage_LATENCY_REQUEST    ControllerMessage_Type = 1
)

var ControllerMessage_Type_name = map[int32]string{
	0: "AGENT_INFO_REQUEST",
	1: "LATENCY_REQUEST",
}
var ControllerMessage_Type_value = map[string]int32{
	"AGENT_INFO_REQUEST": 0,
	"LATENCY_REQUEST":    1,
}

func (x ControllerMessage_Type) String() string {
	return proto.EnumName(ControllerMessage_Type_name, int32(x))
}
func (ControllerMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ControllerLatencyRequest_Type int32

const (
	ControllerLatencyRequest_TCP        ControllerLatencyRequest_Type = 0
	ControllerLatencyRequest_ICMP       ControllerLatencyRequest_Type = 1
	ControllerLatencyRequest_TRACEROUTE ControllerLatencyRequest_Type = 2
)

var ControllerLatencyRequest_Type_name = map[int32]string{
	0: "TCP",
	1: "ICMP",
	2: "TRACEROUTE",
}
var ControllerLatencyRequest_Type_value = map[string]int32{
	"TCP":        0,
	"ICMP":       1,
	"TRACEROUTE": 2,
}

func (x ControllerLatencyRequest_Type) String() string {
	return proto.EnumName(ControllerLatencyRequest_Type_name, int32(x))
}
func (ControllerLatencyRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

type AgentMessage struct {
	Type   AgentMessage_Type `protobuf:"varint,1,opt,name=type,enum=messages.AgentMessage_Type" json:"type,omitempty"`
	Id     string            `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Auth   string            `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
	Result *AgentProbeResult `protobuf:"bytes,4,opt,name=result" json:"result,omitempty"`
	Info   *AgentInfo        `protobuf:"bytes,5,opt,name=info" json:"info,omitempty"`
}

func (m *AgentMessage) Reset()                    { *m = AgentMessage{} }
func (m *AgentMessage) String() string            { return proto.CompactTextString(m) }
func (*AgentMessage) ProtoMessage()               {}
func (*AgentMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AgentMessage) GetType() AgentMessage_Type {
	if m != nil {
		return m.Type
	}
	return AgentMessage_HELLO
}

func (m *AgentMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentMessage) GetAuth() string {
	if m != nil {
		return m.Auth
	}
	return ""
}

func (m *AgentMessage) GetResult() *AgentProbeResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AgentMessage) GetInfo() *AgentInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type AgentInfo struct {
	Os           string `protobuf:"bytes,1,opt,name=os" json:"os,omitempty"`
	Hostname     string `protobuf:"bytes,2,opt,name=hostname" json:"hostname,omitempty"`
	AgentVersion string `protobuf:"bytes,3,opt,name=agentVersion" json:"agentVersion,omitempty"`
	Ipaddress    string `protobuf:"bytes,4,opt,name=ipaddress" json:"ipaddress,omitempty"`
	Label        string `protobuf:"bytes,5,opt,name=label" json:"label,omitempty"`
	Location     string `protobuf:"bytes,6,opt,name=location" json:"location,omitempty"`
}

func (m *AgentInfo) Reset()                    { *m = AgentInfo{} }
func (m *AgentInfo) String() string            { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()               {}
func (*AgentInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AgentInfo) GetOs() string {
	if m != nil {
		return m.Os
	}
	return ""
}

func (m *AgentInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *AgentInfo) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentInfo) GetIpaddress() string {
	if m != nil {
		return m.Ipaddress
	}
	return ""
}

func (m *AgentInfo) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AgentInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type AgentProbeResult struct {
	Type      AgentProbeResult_Type `protobuf:"varint,1,opt,name=type,enum=messages.AgentProbeResult_Type" json:"type,omitempty"`
	ResultId  string                `protobuf:"bytes,2,opt,name=resultId" json:"resultId,omitempty"`
	Host      string                `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	ProbeId   string                `protobuf:"bytes,4,opt,name=probeId" json:"probeId,omitempty"`
	Timestamp int64                 `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Data      []byte                `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AgentProbeResult) Reset()                    { *m = AgentProbeResult{} }
func (m *AgentProbeResult) String() string            { return proto.CompactTextString(m) }
func (*AgentProbeResult) ProtoMessage()               {}
func (*AgentProbeResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AgentProbeResult) GetType() AgentProbeResult_Type {
	if m != nil {
		return m.Type
	}
	return AgentProbeResult_TCP
}

func (m *AgentProbeResult) GetResultId() string {
	if m != nil {
		return m.ResultId
	}
	return ""
}

func (m *AgentProbeResult) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AgentProbeResult) GetProbeId() string {
	if m != nil {
		return m.ProbeId
	}
	return ""
}

func (m *AgentProbeResult) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AgentProbeResult) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ControllerMessage struct {
	Type           ControllerMessage_Type    `protobuf:"varint,1,opt,name=type,enum=messages.ControllerMessage_Type" json:"type,omitempty"`
	LatencyRequest *ControllerLatencyRequest `protobuf:"bytes,2,opt,name=latencyRequest" json:"latencyRequest,omitempty"`
}

func (m *ControllerMessage) Reset()                    { *m = ControllerMessage{} }
func (m *ControllerMessage) String() string            { return proto.CompactTextString(m) }
func (*ControllerMessage) ProtoMessage()               {}
func (*ControllerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ControllerMessage) GetType() ControllerMessage_Type {
	if m != nil {
		return m.Type
	}
	return ControllerMessage_AGENT_INFO_REQUEST
}

func (m *ControllerMessage) GetLatencyRequest() *ControllerLatencyRequest {
	if m != nil {
		return m.LatencyRequest
	}
	return nil
}

type ControllerLatencyRequest struct {
	Type       ControllerLatencyRequest_Type `protobuf:"varint,1,opt,name=type,enum=messages.ControllerLatencyRequest_Type" json:"type,omitempty"`
	ResultId   string                        `protobuf:"bytes,2,opt,name=resultId" json:"resultId,omitempty"`
	Host       string                        `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Parameters map[string]string             `protobuf:"bytes,4,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ControllerLatencyRequest) Reset()                    { *m = ControllerLatencyRequest{} }
func (m *ControllerLatencyRequest) String() string            { return proto.CompactTextString(m) }
func (*ControllerLatencyRequest) ProtoMessage()               {}
func (*ControllerLatencyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ControllerLatencyRequest) GetType() ControllerLatencyRequest_Type {
	if m != nil {
		return m.Type
	}
	return ControllerLatencyRequest_TCP
}

func (m *ControllerLatencyRequest) GetResultId() string {
	if m != nil {
		return m.ResultId
	}
	return ""
}

func (m *ControllerLatencyRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ControllerLatencyRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentMessage)(nil), "messages.AgentMessage")
	proto.RegisterType((*AgentInfo)(nil), "messages.AgentInfo")
	proto.RegisterType((*AgentProbeResult)(nil), "messages.AgentProbeResult")
	proto.RegisterType((*ControllerMessage)(nil), "messages.ControllerMessage")
	proto.RegisterType((*ControllerLatencyRequest)(nil), "messages.ControllerLatencyRequest")
	proto.RegisterEnum("messages.AgentMessage_Type", AgentMessage_Type_name, AgentMessage_Type_value)
	proto.RegisterEnum("messages.AgentProbeResult_Type", AgentProbeResult_Type_name, AgentProbeResult_Type_value)
	proto.RegisterEnum("messages.ControllerMessage_Type", ControllerMessage_Type_name, ControllerMessage_Type_value)
	proto.RegisterEnum("messages.ControllerLatencyRequest_Type", ControllerLatencyRequest_Type_name, ControllerLatencyRequest_Type_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xdf, 0x8e, 0xd2, 0x4e,
	0x14, 0xc7, 0x77, 0x4a, 0x97, 0xa5, 0x07, 0xc2, 0xf6, 0x37, 0xfb, 0x8b, 0x69, 0xd0, 0x44, 0xd2,
	0x1b, 0xf0, 0x06, 0x93, 0xe2, 0x85, 0xd1, 0x78, 0x41, 0x48, 0x55, 0x0c, 0x0b, 0x38, 0x5b, 0x4c,
	0xbc, 0xda, 0x0c, 0xdb, 0xd9, 0xdd, 0xc6, 0xd2, 0xa9, 0x9d, 0xc1, 0x84, 0x67, 0xf2, 0x39, 0xbc,
	0xf1, 0x4d, 0xbc, 0xf1, 0x19, 0xcc, 0x0c, 0x6d, 0xf9, 0xa3, 0x1b, 0x35, 0xde, 0xcd, 0x39, 0x9c,
	0xef, 0x39, 0xf3, 0x99, 0xef, 0x29, 0xd0, 0x5c, 0x32, 0x21, 0xe8, 0x0d, 0x13, 0xbd, 0x34, 0xe3,
	0x92, 0xe3, 0x5a, 0x11, 0xbb, 0xdf, 0x10, 0x34, 0x06, 0x37, 0x2c, 0x91, 0xe7, 0x9b, 0x0c, 0x7e,
	0x0c, 0xa6, 0x5c, 0xa7, 0xcc, 0x41, 0x6d, 0xd4, 0x6d, 0x7a, 0xf7, 0x7b, 0xa5, 0x72, 0xb7, 0xaa,
	0x17, 0xac, 0x53, 0x46, 0x74, 0x21, 0x6e, 0x82, 0x11, 0x85, 0x8e, 0xd1, 0x46, 0x5d, 0x8b, 0x18,
	0x51, 0x88, 0x31, 0x98, 0x74, 0x25, 0x6f, 0x9d, 0x8a, 0xce, 0xe8, 0x33, 0xf6, 0xa0, 0x9a, 0x31,
	0xb1, 0x8a, 0xa5, 0x63, 0xb6, 0x51, 0xb7, 0xee, 0xb5, 0x0e, 0xda, 0xce, 0x32, 0xbe, 0x60, 0x44,
	0x57, 0x90, 0xbc, 0x12, 0x77, 0xc0, 0x8c, 0x92, 0x6b, 0xee, 0x1c, 0x6b, 0xc5, 0xd9, 0x81, 0x62,
	0x94, 0x5c, 0x73, 0xa2, 0x0b, 0xdc, 0x0e, 0x98, 0xea, 0x3a, 0xd8, 0x82, 0xe3, 0xd7, 0xfe, 0x78,
	0x3c, 0xb5, 0x8f, 0x30, 0x40, 0x95, 0xf8, 0x17, 0xf3, 0x71, 0x60, 0x23, 0x5c, 0x03, 0x73, 0x34,
	0x79, 0x39, 0xb5, 0x0d, 0xf7, 0x33, 0x02, 0xab, 0x14, 0xab, 0x7b, 0x73, 0xa1, 0x31, 0x2d, 0x62,
	0x70, 0x81, 0x5b, 0x50, 0xbb, 0xe5, 0x42, 0x26, 0x74, 0xc9, 0x72, 0x9a, 0x32, 0xc6, 0x2e, 0x34,
	0xa8, 0x12, 0xbe, 0x63, 0x99, 0x88, 0x78, 0x92, 0xb3, 0xed, 0xe5, 0xf0, 0x03, 0xb0, 0xa2, 0x94,
	0x86, 0x61, 0xc6, 0x84, 0xd0, 0x98, 0x16, 0xd9, 0x26, 0xf0, 0xff, 0x70, 0x1c, 0xd3, 0x05, 0x8b,
	0x35, 0x8e, 0x45, 0x36, 0x81, 0x9a, 0x19, 0xf3, 0x2b, 0x2a, 0x55, 0xcf, 0xea, 0x66, 0x66, 0x11,
	0xbb, 0xdf, 0x11, 0xd8, 0x87, 0x8f, 0x83, 0xfb, 0x7b, 0xee, 0x3c, 0xbc, 0xfb, 0x19, 0x77, 0x1d,
	0x6a, 0x41, 0x6d, 0xf3, 0xa6, 0xa3, 0xc2, 0xa7, 0x32, 0x56, 0x6e, 0x29, 0xca, 0xc2, 0x2d, 0x75,
	0xc6, 0x0e, 0x9c, 0xa4, 0xaa, 0xd3, 0x28, 0xcc, 0x39, 0x8a, 0x50, 0x31, 0xca, 0x68, 0xc9, 0x84,
	0xa4, 0xcb, 0x54, 0x93, 0x54, 0xc8, 0x36, 0xa1, 0x7a, 0x85, 0x54, 0x52, 0x4d, 0xd2, 0x20, 0xfa,
	0xec, 0x3e, 0xca, 0xcd, 0x39, 0x81, 0x4a, 0x30, 0x9c, 0xd9, 0x47, 0xda, 0x8e, 0xe1, 0xf9, 0xcc,
	0x46, 0xb8, 0x09, 0x10, 0x90, 0xc1, 0xd0, 0x27, 0xd3, 0x79, 0xe0, 0xdb, 0x86, 0xfb, 0x15, 0xc1,
	0x7f, 0x43, 0x9e, 0xc8, 0x8c, 0xc7, 0x31, 0xcb, 0x8a, 0x7d, 0x7c, 0xb2, 0x47, 0xdc, 0xde, 0x12,
	0xff, 0x54, 0xba, 0x8b, 0xfc, 0x06, 0x9a, 0x31, 0x95, 0x2c, 0xb9, 0x5a, 0x13, 0xf6, 0x71, 0xc5,
	0x84, 0xd4, 0xe0, 0x75, 0xcf, 0xfd, 0x95, 0x7e, 0xbc, 0x57, 0x49, 0x0e, 0x94, 0x6e, 0x3f, 0x47,
	0xb8, 0x07, 0x78, 0xf0, 0xca, 0x9f, 0x04, 0x97, 0x6a, 0x9d, 0x2e, 0x89, 0xff, 0x76, 0xee, 0x5f,
	0x04, 0xf6, 0x11, 0x3e, 0x83, 0xd3, 0xf1, 0x20, 0xf0, 0x27, 0xc3, 0xf7, 0x65, 0x12, 0xb9, 0x5f,
	0x0c, 0x70, 0xee, 0x9a, 0x80, 0x9f, 0xef, 0x31, 0x75, 0x7e, 0x7f, 0xa7, 0x7f, 0x71, 0x93, 0x00,
	0xa4, 0x34, 0xa3, 0x4b, 0x26, 0x59, 0xa6, 0x16, 0xb3, 0xd2, 0xad, 0x7b, 0xde, 0x1f, 0x8c, 0x9c,
	0x95, 0x22, 0x3f, 0x91, 0xd9, 0x9a, 0xec, 0x74, 0x69, 0xbd, 0x80, 0xd3, 0x83, 0x9f, 0xb1, 0x0d,
	0x95, 0x0f, 0x6c, 0x9d, 0x7f, 0x4f, 0xea, 0xa8, 0x56, 0xfe, 0x13, 0x8d, 0x57, 0xc5, 0xd7, 0xb4,
	0x09, 0x9e, 0x19, 0x4f, 0xd1, 0x5f, 0x2c, 0xc5, 0xa2, 0xaa, 0xff, 0xb0, 0xfa, 0x3f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x9a, 0xf8, 0x2a, 0xf5, 0xc2, 0x04, 0x00, 0x00,
}
